CREATE SCHEMA RESUME AUTHORIZATION RESUME_ADMIN;

CREATE TABLE RESUME.FN_CONTACT_INFO
(
	ID			INT		PRIMARY KEY		NOT NULL,
	NAME		TEXT					NOT NULL,
	CITY		TEXT					NOT NULL,
	STATE		TEXT					NOT NULL,
	PHONE		TEXT					NOT NULL,
	EMAIL		TEXT					NOT NULL,
	GITHUB		TEXT							,
	LINKEDIN	TEXT
);

CREATE TABLE RESUME.FN_EDUCATION
(
	SCHOOL_ID		INT		PRIMARY KEY		NOT NULL,
	INSITUTION		TEXT					NOT NULL,
	CITY			TEXT					NOT NULL,
	STATE			TEXT					NOT NULL,
	DEGREE_TYPE		TEXT					NOT NULL,
	MAJOR			TEXT					NOT NULL,
	GPA				TEXT					NOT NULL,
	LATIN_HONORS	TEXT							,
	CONFERRAL_DATE	TEXT					NOT NULL
);

CREATE TABLE RESUME.FN_AWARDS
(
	ID			INT		PRIMARY KEY									NOT NULL,
	SCHOOL_ID	INT		REFERENCES	RESUME.FN_EDUCATION(SCHOOL_ID)	NOT NULL,
	NAME		TEXT												NOT NULL,
	DATE		TEXT												NOT NULL
);

CREATE TABLE RESUME.FN_COURSEWORK
(
	ID			INT		PRIMARY KEY									NOT NULL,
	SCHOOL_ID	INT		REFERENCES	RESUME.FN_EDUCATION(SCHOOL_ID)	NOT NULL,
	COURSE		TEXT												NOT NULL
);

CREATE TABLE RESUME.FN_WORK_EXPERIENCE
(
	JOB_ID		INT		PRIMARY KEY		NOT NULL,
	COMPANY		TEXT					NOT NULL,
	CITY		TEXT					NOT NULL,
	STATE		TEXT					NOT NULL,
	TITLE		TEXT					NOT NULL,
	START_DATE	TEXT					NOT NULL,
	END_DATE	TEXT
);

CREATE TABLE RESUME.FN_WORK_RESPONSIBILITIES
(
	ID				INT		PRIMARY KEY										NOT NULL,
	JOB_ID			INT		REFERENCES	RESUME.FN_WORK_EXPERIENCE(JOB_ID)	NOT NULL,
	RESPONSIBILITY	TEXT
);

CREATE TABLE RESUME.FN_PROJECTS
(
	PROJECT_ID	INT		PRIMARY KEY		NOT NULL,
	NAME		TEXT					NOT NULL,
	PURPOSE		TEXT					NOT NULL,
	START_DATE	TEXT					NOT NULL,
	END_DATE	TEXT
);

CREATE TABLE RESUME.FN_PROJECT_DETAILS
(
	ID			INT		PRIMARY KEY									NOT NULL,
	PROJECT_ID	INT 	REFERENCES 	RESUME.FN_PROJECTS(PROJECT_ID)	NOT NULL,
	DETAIL		TEXT
);

CREATE TABLE RESUME.FN_PROGRAMMING_LANGUAGES
(
	ID						INT		PRIMARY KEY		NOT NULL,
	PROGRAMMING_LANGUAGE	TEXT					NOT NULL
);

CREATE TABLE RESUME.FN_TECHNOLOGIES
(
	ID			INT		PRIMARY KEY		NOT NULL,
	TECHNOLOGY	TEXT					NOT NULL
);

CREATE TABLE RESUME.FN_EXTRACURRICULARS
(
	ID			INT		PRIMARY KEY		NOT NULL,
	TITLE		TEXT					NOT NULL,
	START_DATE	TEXT					NOT NULL,
	END_DATE	TEXT					NOT NULL
);